stages:
  - verify

verify:
  image: hugomods/hugo:exts-0.125.7
  stage: verify
  script:
    - hugo --minify --gc --destination public
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
